name: CPI Undeploy iFlow

on:
  workflow_dispatch:
    inputs:
      integrationFlowId:
        description: "Enter CPI iFlow ID, example: Sampletest"
        required: true
        type: string

jobs:
  undeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Piper
        run: |
          curl -L https://github.com/SAP/jenkins-library/releases/latest/download/piper -o piper
          chmod +x piper

      - name: Undeploy CPI Artifact
        env:
          PIPER_apiServiceKey: ${{ secrets.PIPER_apiServiceKey }}
        run: |
          ./piper integrationArtifactUnDeploy \
            --integrationFlowId "${{ github.event.inputs.integrationFlowId }}"
