name: CPI Download to GitHub

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Piper
        run: |
          curl -L https://github.com/SAP/jenkins-library/releases/latest/download/piper -o piper
          chmod +x piper

      - name: Download CPI Artifact
        env:
          PIPER_apiServiceKey: ${{ secrets.PIPER_apiServiceKey }}
        run: |
          ./piper integrationArtifactDownload \
            --integrationFlowId "ExternalLoggingPOC" \
            --integrationFlowVersion "active" \
            --downloadPath "./cpi-artifacts"

      - name: Commit and Push to Repo
        run: |
          git config user.name "cpi-bot"
          git config user.email "cpi-bot@github.com"

          rm -f piper

          git add cpi-artifacts/
          git commit -m "Backup ExternalLoggingPOC from SAP CPI" || echo "No changes"

          git push
