name: Scheduled CPI Deploy

on:
  workflow_dispatch:
    inputs:
      packageName:
        description: "Enter Package Name, example: test or test-123"
        required: true
        type: string

      iflowNames:
        description: "Enter multiple iFlows separated by comma"
        required: true
        type: string

      deploymentDateTime:
        description: "Deployment Date & Time IST (YYYY-MM-DD HH:MM), example: 2026-05-20 22:30"
        required: true
        type: string

jobs:
  wait-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print Deployment Inputs
        run: |
          echo "Package: ${{ github.event.inputs.packageName }}"
          echo "iFlows: ${{ github.event.inputs.iflowNames }}"
          echo "Deployment DateTime IST: ${{ github.event.inputs.deploymentDateTime }}"

      - name: Install Piper
        run: |
          curl -L https://github.com/SAP/jenkins-library/releases/latest/download/piper -o piper
          chmod +x piper

      - name: Wait Until Scheduled Time
        run: |
          TARGET="${{ github.event.inputs.deploymentDateTime }}"

          TARGET_EPOCH=$(TZ="Asia/Kolkata" date -d "$TARGET" +%s)
          CURRENT_EPOCH=$(TZ="Asia/Kolkata" date +%s)

          WAIT_SECONDS=$((TARGET_EPOCH - CURRENT_EPOCH))

          echo "Current IST Time: $(TZ="Asia/Kolkata" date)"
          echo "Deployment IST Time: $TARGET"

          if [ "$WAIT_SECONDS" -gt 0 ]; then
            echo "Waiting $WAIT_SECONDS seconds..."
            sleep $WAIT_SECONDS
          else
            echo "Deployment time already passed"
            exit 1
          fi

      - name: Deploy Selected iFlows
        env:
          PIPER_apiServiceKey: ${{ secrets.PIPER_apiServiceKey }}
        run: |
          PACKAGE="${{ github.event.inputs.packageName }}"
          echo "Selected Package: $PACKAGE"

          IFS=',' read -ra FLOWS <<< "${{ github.event.inputs.iflowNames }}"

          for FLOW in "${FLOWS[@]}"
          do
            FLOW=$(echo "$FLOW" | xargs)

            if [ -z "$FLOW" ]; then
              continue
            fi

            echo "Deploying iFlow: $FLOW from package: $PACKAGE"

            ./piper integrationArtifactDeploy \
              --integrationFlowId "$FLOW"
          done

      - name: Deployment Complete
        run: |
          echo "Scheduled deployment completed successfully"
